version: v.2.0.0
pidfile: ./jobserver.pid
retrystartup: true
cluster:
  hosts: 192.168.2.80:2181,192.168.2.81:2181,192.168.2.82:2181
  root: /cloudtask
  pulse: 30s
  timeout: 60s
  threshold: 1
api:
  hosts: [":8985"]
  enablecors: true
scheduler:
  allocmode: hash
  allocrecovery: 320s
cache:
  lrusize: 1024
  storage:
      mongo:
        hosts: 192.168.2.80:27017,192.168.2.81:27017,192.168.2.82:27017
        database: cloudtask
        #auth: {
        #  user: datastoreAdmin,
        #  password: ds4dev
        #}
        options: [
          "maxPoolSize=20",
          "replicaSet=mgoCluster",
		      #"authSource=admin"
        ]
notifications:
    endpoints:
      - name: smtp
        host: smtp.example.com
        port: 25
        user: 
        password: 
        sender: cloudtask@example.com
        enabled: true
logger:
    logfile: ./logs/jobserver.log
    loglevel: info
    logsize: 20971520
...
